version: 2

sources:
  - name: spectacle
    description: Ingestion brute des dataset data.gouv.fr/declaration des entrepreneurs spectacles vivants et /liste de spectacles vivants
    database: licences-spectacles
    schema: spectacle
    tables:
      - name: lic_spec_full
        description: déclaration des entrepreneurs de spectacle vivants depuis 2020
        columns:
          - name: _airbyte_extracted_at
          - name: numero_de_recepisse
            description: Primary key 

          - name: date_de_depot_de_la_declaration_inscrite_sur_le_recepisse
          - name: date_de_validite_du_recepisse_sauf_opposition_de_l_administration
          - name: categorie
          - name: type
          - name: region
          - name: geoloc_cp
          - name: nom_du_lieu
          - name: code_naf_ape
          - name: departement
          - name: type_de_declarant
          - name: code_postal_du_lieu
          - name: statut_du_recepisse
          - name: siren_personne_physique_siret_personne_morale
          - name: raison_sociale_personne_morale_ou_nom_personne_physique
          - name: code_postal_de_l_etablissement_principal_personne_morale_ou_de_la_personne_physique 

      - name: liste_festivals
        description : liste festivals
        database: licences-spectacles
        schema: liste_festivals
        columns:
          - name : identifiant
          - name : geocodage_xy
          - name : adresse_e_mail
          - name : nom_de_la_voie
          - name : numero_de_voie
          - name : adresse_postale
          - name : identifiant_cnm
          - name : nom_du_festival
          - name : code_insee_commune
          - name : discipline_dominante
          - name : identifiant_agence_a
          - name : envergure_territoriale
          - name : sous_categorie_musique
          - name : site_internet_du_festival
          - name : sous_categorie_musique_cnm
          - name : annee_de_creation_du_festival
          - name : libelle_epci_collage_en_valeur
          - name : complement_d_adresse_facultatif
          - name : sous_categorie_spectacle_vivant
          - name : decennie_de_creation_du_festival
          - name : region_principale_de_deroulement
          - name : code_insee_epci_collage_en_valeur
          - name : commune_principale_de_deroulement
          - name : sous_categorie_livre_et_litterature
          - name : departement_principal_de_deroulement
          - name : sous_categorie_cinema_et_audiovisuel
          - name : type_de_voie_rue_avenue_boulevard_etc
          - name : periode_principale_de_deroulement_du_festival
          - name : sous_categorie_arts_visuels_et_arts_numeriques
          - name : code_postal_de_la_commune_principale_de_deroulement

